version: '3'

services:
  mongodb:
    image: mongo
    container_name: mongo
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=jef
      - MONGO_INITDB_ROOT_PASSWORD=mongopw
    ports:
      - "27017:27017"
  logstash:
    build: .
    container_name: logstash
    restart: always
    depends_on:
      - mongodb 
    ports:
      - "514:1514/udp"
    volumes:
      - ~/git/elk/logstash/logstash-pipeline.conf:/usr/share/logstash/pipeline/logstash.conf
      - ~/git/elk/logstash/logstash.yml:/usr/share/logstash/config/logstash.yml
